<?php
$equadio_slider_sc = equadio_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $equadio_slider_sc ) && strpos( $equadio_slider_sc, '[' ) !== false && strpos( $equadio_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( equadio_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$equadio_anchor_icon = equadio_get_theme_option( 'front_page_title_anchor_icon' );
		$equadio_anchor_text = equadio_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $equadio_anchor_icon ) || ! empty( $equadio_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $equadio_anchor_icon ) ? ' icon="' . esc_attr( $equadio_anchor_icon ) . '"' : '' )
									. ( ! empty( $equadio_anchor_text ) ? ' title="' . esc_attr( $equadio_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $equadio_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$equadio_scheme = equadio_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $equadio_scheme ) && ! equadio_is_inherit( $equadio_scheme ) ) {
			echo ' scheme_' . esc_attr( $equadio_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( equadio_get_theme_option( 'front_page_title_paddings' ) );
		if ( equadio_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$equadio_css      = '';
		$equadio_bg_image = equadio_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $equadio_bg_image ) ) {
			$equadio_css .= 'background-image: url(' . esc_url( equadio_get_attachment_url( $equadio_bg_image ) ) . ');';
		}
		if ( ! empty( $equadio_css ) ) {
			echo ' style="' . esc_attr( $equadio_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$equadio_anchor_icon = equadio_get_theme_option( 'front_page_title_anchor_icon' );
		$equadio_anchor_text = equadio_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $equadio_anchor_icon ) || ! empty( $equadio_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $equadio_anchor_icon ) ? ' icon="' . esc_attr( $equadio_anchor_icon ) . '"' : '' )
									. ( ! empty( $equadio_anchor_text ) ? ' title="' . esc_attr( $equadio_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( equadio_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' equadio-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$equadio_css      = '';
			$equadio_bg_mask  = equadio_get_theme_option( 'front_page_title_bg_mask' );
			$equadio_bg_color_type = equadio_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $equadio_bg_color_type ) {
				$equadio_bg_color = equadio_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $equadio_bg_color_type ) {
				$equadio_bg_color = equadio_get_scheme_color( 'bg_color', $equadio_scheme );
			} else {
				$equadio_bg_color = '';
			}
			if ( ! empty( $equadio_bg_color ) && $equadio_bg_mask > 0 ) {
				$equadio_css .= 'background-color: ' . esc_attr(
					1 == $equadio_bg_mask ? $equadio_bg_color : equadio_hex2rgba( $equadio_bg_color, $equadio_bg_mask )
				) . ';';
			}
			if ( ! empty( $equadio_css ) ) {
				echo ' style="' . esc_attr( $equadio_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$equadio_caption = equadio_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $equadio_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $equadio_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $equadio_caption, 'equadio_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$equadio_description = equadio_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $equadio_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $equadio_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $equadio_description ), 'equadio_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( equadio_get_theme_option( 'front_page_title_button1_link' ) != '' || equadio_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						equadio_show_layout( equadio_customizer_partial_refresh_front_page_title_button1_link() );
						equadio_show_layout( equadio_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
